In [1]:
import numpy as np
import time

from mzpy.mzMatch import MSList
from mzpy import mzPandas as mpd

In [2]:
mdf = mpd.read_msp('../test_data/Msp_M1649.msp')
mdf['Num Peaks'] = mdf['Num Peaks'].astype(int)
mdf = mdf[mdf['Num Peaks'] > 0].reset_index()
mdf.shape

(440, 9)

In [ ]:
ref = MSList(mdf.head(10)['PRECURSORMZ'], mdf.head(10)['msms'])
que = MSList(mdf.head(10)['PRECURSORMZ'], mdf.head(10)['msms'])

In [5]:
mzMatch._cosine_(msl[0], msl[100])

-1.0

In [14]:
type(msl)

mzpy.mzMatch.MSList

In [ ]:
isinstance(msl, )

MSList([array([[131.53354   , 100.        ],
        [115.96429   ,  49.40772556],
        [109.94377   ,   7.89980281],
        [ 99.51256   ,  40.49433487],
        [ 88.00468   , 100.        ],
        [ 77.99928   ,  43.79130581],
        [ 72.93768   ,  19.44552434],
        [ 67.51047   ,   9.07170525],
        [ 57.93547   ,  44.26624949]])
 array([[111.02042   , 100.        ],
        [ 99.94831   ,  36.17304493],
        [ 87.00449   , 100.        ],
        [ 77.99928   ,  70.62831788],
        [ 72.93766   ,  70.63782585],
        [ 55.93511   ,  58.43752476]])
 array([[199.00098   , 100.        ],
        [157.97438   ,  80.65495944],
        [132.95821   ,  56.08070649],
        [116.97205   , 100.        ],
        [ 98.97568   ,  79.27835776],
        [ 74.93803   ,  46.31175382],
        [ 72.93768   ,  56.18065262],
        [ 70.95842   ,  41.79856171],
        [ 57.93546   ,  74.81279623]])
 array([[196.00392   , 100.        ],
        [132.95822   ,  48.21354302],
  

In [6]:
msl[101]

array([[130.15904   , 100.        ],
       [100.11238   ,  14.45954825],
       [ 86.09689   , 100.        ],
       [ 58.0658    ,  15.90099125]])

In [8]:
for msms in msl:
    if abs(msms[0, 0] - 130.15904) < 0.003:
        refms = msms
        break

In [ ]:
_cosine_ = mzMatch._cosine_



In [10]:
mzMatch._cosine_(msl[101], refms)

np.float64(0.8645633438748792)